version: '3.5'

services:
  postgres:
    image: postgres
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: