name: academy_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  get_it: ^7.2.0
  mongo_dart: ^0.9.1
  db:
    path: packages/db
  shared:
    path: packages/shared
  stormberry: ^0.12.1

  

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
