// This file is "model.dart"
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'db_models.schema.dart';

@Model()
abstract class DbUser {
  @PrimaryKey()
  @AutoIncrement()
  int get id;

  String get name;
}
